### PR TITLE
add 1 static block

### PR DESCRIPTION
**Pull request by AbrahamWang484**
good

### CODE REVIEW

**Review by AbrahamWang484 — COMMENTED** [review]
please add more

**Comment by ABChaos8** [comment]
great code

**Comment by olegiakim** [comment]
Awesome!

**Review by AbrahamWang484 — COMMENTED** [review]
please team members approve it.
thank you!

**Review by olegiakim — COMMENTED** [review]
Awesome Code!

**Comment by AbrahamWang484** [comment]
thank you !

**Pull request merged**
